import localFont from "next/font/local";
import type { Metadata } from "next";
import Script from "next/script";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import { AuthProvider } from "@/lib/auth/AuthProvider";

// Setup your custom font
const segoeUI = localFont({
  src: "./fonts/SegoeUI-VF.woff2",
  display: "swap",
  variable: "--font-segoe",
});

// Metadata for your app
export const metadata: Metadata = {
  title: "Neuron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = "secure-nonce"; // Replace with dynamic nonce in production

  return (
    <html lang="en">
      <head>
        {/* ✅ Proper way to load Google Identity script */}
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
          nonce={nonce}
        />
      </head>
      <body className={`${segoeUI.variable} antialiased`}>
        <Toaster />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}