import localFont from "next/font/local";
import type { Metadata } from "next";

import "./globals.css";

const segoeUI = localFont({
  src: './fonts/SegoeUI-VF.woff2',
  display: 'swap',
  variable: '--font-segoe'
});

export const metadata: Metadata = {
  title: "Neuron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${segoeUI.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}