import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

const segoeUI = localFont({
    src: '../fonts/segoeUI-VF.ttf',
    display: 'swap',
    variable: '--font-segoeUi',
});

export const metadata: Metadata = {
    title: "Neuron",
    description: "Generated by create next app",
};

export default function CloudLayout({
    children, header
}: Readonly<{
    children: React.ReactNode;
    header?: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${segoeUI.variable} antialiased`}
            >
                <div className="grid grid-cols-12 min-h-screen" style={{background: "linear-gradient(20deg , #e2f0fb 40%, #fad0ec 70%, #F5D4CB 95%, #FAE2D4 100%)"}}>

                    <div className="col-span-12 h-fit">
                        {/* Header Slot */}
                        {header}

                    </div>

                    <div className="col-span-12 gap-5">
                        {/* Content */}
                        {children}
                    </div>

                </div>

            </body>
        </html>
    );
}